# Generated by Django 3.0.7 on 2020-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('method', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('modifiedAt', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=models.Model, to='company.Company')),
            ],
        ),
    ]
